---
- name: Create file using custom module
  my_own_namespace.yandex_cloud_elk.my_own_module:
    path: "{{ my_own_module_path }}"
    content: "{{ my_own_module_content }}"
    force: "{{ my_own_module_force | bool }}"

