---
- name: Test my own role
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: my_own_namespace.yandex_cloud_elk.my_own_role
      vars:
        my_own_module_path: "/tmp/role_test.txt"
        my_own_module_content: "This file was created by role at {{ ansible_date_time.iso8601 }}"
        my_own_module_force: false

